"""
from sqlalchemy import create_engine
import pandas as pd

db_connection_str = create_engine("mysql://root:2514@localhost/trackman")
db_connection = create_engine(db_connection_str)
df = pd.read_sql('SELECT * FROM test_track_data limit 10', con=db_connection)
"""

#tr '\r' '\n' < yourfile.csv > yourfile-unix.csv

import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="2514",
  database="immigration"
)

mycursor = mydb.cursor()

create_table_str = """
CREATE TABLE h1b_hire_salary
(
    CASE_NUMBER VARCHAR(255) NOT NULL,
    CASE_STATUS VARCHAR(50),
    CASE_SUBMITTED DATE,
    DECISION_DATE DATE,
    ORIGINAL_CERT_DATE DATE,
    VISA_CLASS VARCHAR(50),
    EMPLOYMENT_START_DATE DATE,
    EMPLOYMENT_END_DATE DATE,
    EMPLOYER_NAME TEXT,
    EMPLOYER_BUSINESS_DBA VARCHAR(255),
    EMPLOYER_ADDRESS TEXT,
    EMPLOYER_CITY VARCHAR(50),
    EMPLOYER_STATE VARCHAR(50),
    EMPLOYER_POSTAL_CODE VARCHAR(50),
    EMPLOYER_COUNTRY VARCHAR(50),
    EMPLOYER_PROVINCE VARCHAR(50),
    EMPLOYER_PHONE VARCHAR(50),
    EMPLOYER_PHONE_EXT VARCHAR(50),
    SECONDARY_ENTITY BOOLEAN,
    SECONDARY_ENTITY_BUSINESS_NAME TEXT,
    AGENT_REPRESENTING_EMPLOYER BOOLEAN,
    AGENT_ATTORNEY_NAME TEXT,
    AGENT_ATTORNEY_CITY VARCHAR(50),
    AGENT_ATTORNEY_STATE VARCHAR(50),
    JOB_TITLE TEXT,
    SOC_CODE VARCHAR(255),
    SOC_NAME VARCHAR(255),
    NAICS_CODE VARCHAR(255),
    TOTAL_WORKERS INT,
    NEW_EMPLOYMENT VARCHAR(255),
    CONTINUED_EMPLOYMENT VARCHAR(255),
    CHANGE_PREVIOUS_EMPLOYMENT VARCHAR(255),
    NEW_CONCURRENT_EMPLOYMENT VARCHAR(255),
    CHANGE_EMPLOYER VARCHAR(255),
    AMENDED_PETITION VARCHAR(255),
    FULL_TIME_POSITION BOOLEAN,
    PREVAILING_WAGE FLOAT,
    PW_UNIT_OF_PAY VARCHAR(20),
    PW_WAGE_LEVEL VARCHAR(20),
    PW_SOURCE VARCHAR(20),
    PW_SOURCE_OTHER VARCHAR(255),
    WAGE_RATE_OF_PAY_FROM FLOAT,
    WAGE_RATE_OF_PAY_TO FLOAT,
    WAGE_UNIT_OF_PAY VARCHAR(20),
    H1B_DEPENDENT BOOLEAN,
    WORKSITE_CITY VARCHAR(50),
    WORKSITE_COUNTY VARCHAR(50),
    WORKSITE_STATE VARCHAR(50),
    WORKSITE_POSTAL_CODE VARCHAR(50),
    WILLFUL_VIOLATOR BOOLEAN,
    SUPPORT_H1B VARCHAR(20),
    STATUTORY_BASIS VARCHAR(20),
    MASTERS_EXEMPTION BOOLEAN,
    APPX_A_NO_OF_EXEMPT_WORKER_1 SMALLINT,
    APPX_A_NAME_OF_INSTITUTION_1 VARCHAR(255),
    APPX_A_FIELD_OF_STUDY_1 VARCHAR(255),
    APPX_A_DATE_OF_DEGREE_1 DATE,
    APPX_A_NO_OF_EXEMPT_WORKER_2 SMALLINT,
    APPX_A_NAME_OF_INSTITUTION_2 VARCHAR(255),
    APPX_A_FIELD_OF_STUDY_2 VARCHAR(255),
    APPX_A_DATE_OF_DEGREE_2 DATE,
    APPX_A_NO_OF_EXEMPT_WORKER_3 SMALLINT,
    APPX_A_NAME_OF_INSTITUTION_3 VARCHAR(255),
    APPX_A_FIELD_OF_STUDY_3 VARCHAR(255),
    APPX_A_DATE_OF_DEGREE_3 DATE,
    APPX_A_NO_OF_EXEMPT_WORKER_4 SMALLINT,
    APPX_A_NAME_OF_INSTITUTION_4 VARCHAR(255), 
    APPX_A_FIELD_OF_STUDY_4 VARCHAR(255),
    APPX_A_DATE_OF_DEGREE_4 DATE,
    APPX_A_NO_OF_EXEMPT_WORKER_5 SMALLINT,
    APPX_A_NAME_OF_INSTITUTION_5 VARCHAR(255),
    APPX_A_FIELD_OF_STUDY_5 VARCHAR(255),
    APPX_A_DATE_OF_DEGREE_5 DATE,
    PRIMARY KEY ( CASE_NUMBER )
)
"""


load_data_str = """
LOAD DATA LOCAL INFILE '/Users/Chen/Desktop/h1b_salary/data/H-1B_Disclosure_Data_FY2019.csv' 
INTO TABLE h1b_hire_salary
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\r'
IGNORE 1 LINES 
(
CASE_NUMBER,
CASE_STATUS,
@CASE_SUBMITTED,
@DECISION_DATE,
@ORIGINAL_CERT_DATE,
VISA_CLASS,
@EMPLOYMENT_START_DATE,
@EMPLOYMENT_END_DATE,
EMPLOYER_NAME,
EMPLOYER_BUSINESS_DBA,
EMPLOYER_ADDRESS,
EMPLOYER_CITY,
EMPLOYER_STATE,
EMPLOYER_POSTAL_CODE,
EMPLOYER_COUNTRY,
EMPLOYER_PROVINCE,
EMPLOYER_PHONE,
EMPLOYER_PHONE_EXT,
SECONDARY_ENTITY,
SECONDARY_ENTITY_BUSINESS_NAME,
AGENT_REPRESENTING_EMPLOYER,
AGENT_ATTORNEY_NAME,
AGENT_ATTORNEY_CITY,
AGENT_ATTORNEY_STATE,
JOB_TITLE,
SOC_CODE,
SOC_NAME,
NAICS_CODE,
TOTAL_WORKERS,
NEW_EMPLOYMENT,
CONTINUED_EMPLOYMENT,
CHANGE_PREVIOUS_EMPLOYMENT,
NEW_CONCURRENT_EMPLOYMENT,
CHANGE_EMPLOYER,
AMENDED_PETITION,
FULL_TIME_POSITION,
PREVAILING_WAGE,
PW_UNIT_OF_PAY,
PW_WAGE_LEVEL,
PW_SOURCE,
PW_SOURCE_OTHER,
WAGE_RATE_OF_PAY_FROM,
WAGE_RATE_OF_PAY_TO,
WAGE_UNIT_OF_PAY,
H1B_DEPENDENT,
WORKSITE_CITY,
WORKSITE_COUNTY,
WORKSITE_STATE,
WORKSITE_POSTAL_CODE,
WILLFUL_VIOLATOR,
SUPPORT_H1B,
STATUTORY_BASIS,
MASTERS_EXEMPTION,
APPX_A_NO_OF_EXEMPT_WORKER_1,
APPX_A_NAME_OF_INSTITUTION_1,
APPX_A_FIELD_OF_STUDY_1,
@APPX_A_DATE_OF_DEGREE_1,
APPX_A_NO_OF_EXEMPT_WORKER_2,
APPX_A_NAME_OF_INSTITUTION_2,
APPX_A_FIELD_OF_STUDY_2,
@APPX_A_DATE_OF_DEGREE_2,
APPX_A_NO_OF_EXEMPT_WORKER_3,
APPX_A_NAME_OF_INSTITUTION_3,
APPX_A_FIELD_OF_STUDY_3,
@APPX_A_DATE_OF_DEGREE_3,
APPX_A_NO_OF_EXEMPT_WORKER_4,
APPX_A_NAME_OF_INSTITUTION_4,
APPX_A_FIELD_OF_STUDY_4,
@APPX_A_DATE_OF_DEGREE_4,
APPX_A_NO_OF_EXEMPT_WORKER_5,
APPX_A_NAME_OF_INSTITUTION_5,
APPX_A_FIELD_OF_STUDY_5,
@APPX_A_DATE_OF_DEGREE_5
)
set CASE_SUBMITTED = STR_TO_DATE(@CASE_SUBMITTED, '%m/%d/%Y'),
DECISION_DATE = STR_TO_DATE(@DECISION_DATE, '%m/%d/%Y'),
ORIGINAL_CERT_DATE = STR_TO_DATE(@ORIGINAL_CERT_DATE, '%m/%d/%Y'),
EMPLOYMENT_START_DATE = STR_TO_DATE(@EMPLOYMENT_START_DATE, '%m/%d/%Y'),
EMPLOYMENT_END_DATE = STR_TO_DATE(@EMPLOYMENT_END_DATE, '%m/%d/%Y'),
APPX_A_DATE_OF_DEGREE_1 = STR_TO_DATE(@APPX_A_DATE_OF_DEGREE_1, '%m/%d/%Y'),
APPX_A_DATE_OF_DEGREE_2 = STR_TO_DATE(@APPX_A_DATE_OF_DEGREE_2, '%m/%d/%Y'),
APPX_A_DATE_OF_DEGREE_3 = STR_TO_DATE(@APPX_A_DATE_OF_DEGREE_3, '%m/%d/%Y'),
APPX_A_DATE_OF_DEGREE_4 = STR_TO_DATE(@APPX_A_DATE_OF_DEGREE_4, '%m/%d/%Y'),
APPX_A_DATE_OF_DEGREE_5 = STR_TO_DATE(@APPX_A_DATE_OF_DEGREE_5, '%m/%d/%Y');
;
"""

mycursor.execute(load_data_str)
mydb.commit()
mycursor.close()




